export default {
  HOME_SCREEN: 'Home',
  TEMP_SCREEN: 'Temp',
  CATEGORIES_SCREEN: 'Categories',
  SHOP_SCREEN: 'Shop',
  SUBCATEGORIES_OPTION_SCREEN: 'SubcategoriesOption',
  SUBCATEGORIES_SCREEN: 'SubCategories',
  CATEGORY_SCREEN: 'Category',
  SINGLE_PRODUCT_SCREEN: 'SingleProduct',
  CART_SCREEN: 'Cart',
  SHIPPING_SCREEN: 'Shipping',
  PAYMENT_METHOD_SCREEN: 'PaymentMethod',
  SHIPPING_METHOD_SCREEN: 'ShippingMethod',
  CHECKOUT_SCREEN: 'Checkout',
  ACCOUNT_SCREEN: 'Account',
  PROFILE_SCREEN: 'Profile',
  SAVED_ADDRESS_SCREEN: 'SavedAddress',
  ORDERS_SCREEN: 'Orders',
  RECENTLY_VIEWED_SCREEN: 'RecentlyViewed',
  SAVE_CARDS_SCREEN: 'SaveCards',
  LOGIN_SIGNUP_SCREEN: 'LoginSignUp',
  FORGOT_PASSWORD_SCREEN: 'ForgotPassword',
  ORDER_DETAIL_SCREEN: 'OrderDetail',
  EDIT_PROFILE_SCREEN: 'EditProfile',
  CHANGE_PASSWORD_SCREEN: 'ChangePassword',
};
